name: Hourly CVE Scraper

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:      

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install praw requests beautifulsoup4

      - name: Run scraper
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: python reddit_cve_scraper.py

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add reddit_cve_posts.json
          git commit -m "Update CVE scrape results [bot]" || echo "No changes to commit"
          git push
